# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STUnitasImageSearcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'Alamofire', '4.7.3'
   pod 'Kingfisher'

  # Pods for STUnitasImageSearcher

end
